name: Build dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build command
      run: . ./buildenv d2s

    - name: Archive tools directory
      uses: actions/upload-artifact@v3
      with:
        name: tools-artifact
        path: out/tools

